using System;

/* this is a placeholder on the C# side for the class used as a column key 
 * for the input and output rows used and generated by PMML on the Java side
 */

namespace com.WDataSci.JniPMML
{
    public
    class FieldName
    {
        private String value=null;
        public FieldName() { }
        public FieldName(String arg) { this.value = arg; }
        public String getValue()
        {
            return this.value;
        }
    }
}
